version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    ports: [1025, 1080]
###< symfony/mailer ###

###> symfony/mercure-bundle ###
  mercure:
    environment:
        SERVER_NAME: ":3000"
        CORS_ALLOWED_ORIGINS: http://172.16.10.163:8000 http://172.16.10.163:3000
    ports:
      - "80"
###< symfony/mercure-bundle ###
